### ISSUE TITLE
Inject FLEX.dylib into Sprinboard

### ISSUE THREAD

**Issue by OdNairy** [qiaoxueshi/FLEXLoader#5]
Currently the only way to inject flex into springboard process is manually add key "FLEXLoaderEnabled-com.apple.springboard" into `/var/mobile/Library/Preferences/com.joeyio.FLEXLoader.plist` file. 
We need ability to check Springboard in settings.

**Comment by qiaoxueshi** [comment]
Yes, the only way to inject SpringBoard is what you said..

**Comment by OdNairy** [comment]
Why we cannot just add special switcher for Springboard?

**Comment by qiaoxueshi** [comment]
The switcher is based on an auto-generated app plist. So it may take me some time to add this feature, I   may add this feature in future release. Thanks for your nice feedback.

**Comment by qiaoxueshi** [comment]
Sorry to close it
