### ISSUE TITLE
Updating to latest version of FLEX

### ISSUE THREAD

**Issue by jyounus** [qiaoxueshi/FLEXLoader#6]
Hey there,

Any chance you could update to the latest release of FLEX? Currently FLEXLoader crashes for me when an app is about to show an alert dialog. I did a search on the FLEX repo and found that there was an issue they fixed a while ago. Would be great if you could update this and push a new update on Cydia as well.

Thank you!

**Comment by qiaoxueshi** [comment]
I have submit the 1.3.0 version to the BigBoss, containing FLEX dynamic library is update to 2.3.0 release version. Sorry for so late.

**Comment by jyounus** [comment]
Nice one, thanks a lot! Will check it out some time later and hope it works now! :D

**Comment by qiaoxueshi** [comment]
Thanks for your feedback and support : ] .
