### ISSUE TITLE
Can't find on cydia anymore?

### ISSUE THREAD

**Issue by chibill** [qiaoxueshi/FLEXLoader#9]

**Comment by qiaoxueshi** [comment]
Search 'Flipboard FLEX loader' keyword in Cydia, and you need to add BigBoss Repo Source first , then install

**Comment by chibill** [comment]
I forgot I opened this. I figured out that Cydia forgot about Big Boss ever
when I showed it as installed. To fix the problem I have to rejail break

On Mar 21, 2017 10:01 AM, "Joey" <notifications@github.com> wrote:

Search 'Flipboard FLEX loader' keyword in Cydia, and you need to add
BigBoss Repo Source first , then install

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/qiaoxueshi/FLEXLoader/issues/9#issuecomment-288106518>,
or mute the thread

**Comment by qiaoxueshi** [comment]
Soga, that's OK. 

So I will close the issue later.
